### ISSUE TITLE
No Device Token with iOS 10

### ISSUE THREAD

**Issue by cybeerboy** [taivo/parse-push-plugin#78] opened 2016-10-18 15:21 UTC
Currently we do not receive any device tokens with iOS 10 to send out a push notification with parse push open server. It is working fine with iOS 9.x and below. We added some new rules as described e.g. "gap:" to allow the frame to get trough. No success yet. Could you help us. How can we register successfully an iOS 10 device and get a valid device token?

Java Script Examples are welcome if needed.

![device-token](https://cloud.githubusercontent.com/assets/1481471/19484563/540b9f8a-9558-11e6-8c0b-dd500efb5cb1.png)

Thank you in advance.

**Comment by cybeerboy** [comment] 2016-10-25 07:19
Seems like @otmezger had the same problem:
https://github.com/otmezger/parse-push-plugin/commit/6285d6d981fa38713045e63ca0cd929aafd76d21

Could you check with your code.

**Comment by otmezger** [comment] 2016-10-25 12:13
Hi. Yes, I'm working on it. Currently we basically rewrote the plugin so that it's compatible with iOS 10.  The issue is, the old code was not compatible with iOS 10. The status right now is that we broke the JS connection of the plugin. We get the push notifications in the phone, but can't use them in JS. Stay tuned.

**Comment by cybeerboy** [comment] 2016-10-25 13:51
Thanks otmezger for your quick support and answer. We are happy for any progress.

**Comment by otmezger** [comment] 2016-10-25 14:05
there are so many unconsolidated forks for this plugin. I would be a great help if someone with experience could consolidate them, and make a single, always up-to-date-in-all-platforms plugin.

**Comment by cleever** [comment] 2016-10-25 14:15
@otmezger This fork from Taivo seems to be the best version of this plugin.

**Comment by otmezger** [comment] 2016-10-25 14:26
when I started a few months ago, this plugin was outdated and I opted for the fork referenced above. Now I'm fixing iOS 10 there, but are having trouble with Android. Does this fork work on android and iOS <10? (I'm aware of the iOS 10 bug, but now I know how to fix it).

**Comment by cleever** [comment] 2016-10-25 14:36
I'm using this plugin with android with no issues.

I suggest you to talk with @taivo to consolidate the fixes and improvements of both forks in only one repository.

**Comment by taivo** [comment] 2016-10-25 19:37
Hi all,
Sorry I've been so swamped. Haven't had a chance to replicate this ios 10 issue for myself.

@otmezger , this fork the way it is right now should work for Android and iOS < 10. I'm pretty open to merge contributions so if you feel like submitting a PR, I'm all for it. Are you currently able to tell us the crux of the iOS 10 incompatibility issue?

**Comment by otmezger** [comment] 2016-10-25 20:04
@taivo the problem is that iOS 10 has a new way of registering PN. so basically the plugin has to change. I already did that for another fork, see the link in the second comment. I still have to do some work, after I finish I will try to push here.

**Comment by cybeerboy** [comment] 2016-10-26 06:48
@otmezger @taivo Thank you for helping out. We will test it after you submitted and provide feedback.

**Comment by cybeerboy** [comment] 2016-10-28 07:32
@otmezger any progress you could share?

**Comment by otmezger** [comment] 2016-10-28 15:58
@cybeerboy @taivo I fixed the problem here https://github.com/thefuturehaus/parse-push-plugin/pull/10. I'm still going to keep using this repository as I don't know how to compare if the 2 repositories are "compatible", so please feel free to check my code and implement it over here. Or you can use the @kmorey's fork... or you can help me merging it to @taivo's fork and we join forces (makes the most sense!)

**Comment by cybeerboy** [comment] 2016-11-01 16:17
@taivo Could you be so nice and help us merging the solved issue into your git to make it work? @otmezger @kmorey's fork is not working for us somehow.

**Comment by otmezger** [comment] 2016-11-01 17:46
For me is working perfectly. In fact, here is what we are up to in iOS. We will pushing some of the changes soon:
<img width="533" alt="pushnotification_status_overview_-_google_sheets" src="https://cloud.githubusercontent.com/assets/2758346/19900369/d6a66954-a028-11e6-9bdb-88d835a92621.png">

**Comment by otmezger** [comment] 2016-11-01 17:49
I found that there where 2 different approaches with parse PN and cordova. The first one was having only 1 plugin and not having to alter any file in Xcode manually. The other approach needed coding in Xcode, and we didn't like this approach. I'm not sure which paradigm this fork is using, but @kmorey and mine is using the paradigm where no coding in Xcode is nessearay. Everything is being made by the plugin and javascript.

**Comment by taivo** [comment] 2016-11-01 21:02
@cybeerboy, I feel your pain and I will try to get to this next week. I'm in the middle of a move to a different city right now so I'm completely swamped.

@otmezger This plugin uses the method without coding in Xcode. I originally forked a version that required coding in Xcode, then found that it was too time consuming to make any update to this plugin (and test). That's when I just automated all the Xcode and Java components with sensible defaults. AFAIK, all other forks that doesn't require fussing with Xcode and Java derives from this fork.

**Comment by otmezger** [comment] 2016-11-02 14:24
@taivo Great to hear. So ended the "dark side" of this plugin :-) 

It should be possible to merge, but as I said, I don't have the skills to do it. I'm working now on fixing iOS 10. Its already working, even if the app is completely closed. I'm also working on reporting pushOpens to parse-server (currently not working, looks like a bug on parse-server) and on making possible to reference the user from the Installation class.

**Comment by kmorey** [comment] 2016-11-02 15:18
I'm all for rebasing/merging our fork into this one. We don't actively use it now and so it's difficult for us to maintain. It looks like our forks have a common base but it's farther back than even when I forked off yet another in the history. It's not a simple merge and its possible some of the work has been duplicated along the way.

Might be able to cherry pick the commits along the way, but I don't really know the state of the taivo fork to do it.

**Comment by otmezger** [comment] 2016-11-04 16:26
fyi, we fixed an issue with Bolts being a link instead of having the binary. @cybeerboy please test again. I can also send my code so you can see how I work with it.

**Comment by cybeerboy** [comment] 2016-11-07 07:53
@otmezger We will try today. It would be nice to see some code as reference.

**Comment by IftekharDani** [comment] 2016-11-30 12:02
@taivo Please merge the @otmezger code  OR update the your fork.

**Comment by shagul298** [comment] 2016-12-14 10:25
@taivo Please update your fork.

**Comment by campers** [comment] 2017-01-09 16:08
Does anyone have the time & skills to merge the fixes required? Unfortunately iOS is the one things I have no experience in, I've contributed to Android fixes here. I could put in a couple hundred dollars if that helps someone make the time to get it done.

**Comment by pocketninja** [comment] 2017-01-10 00:18
We need this going for a client project pretty soon seeing as the deadline for Parse shutting down is approaching very quickly.

I've started applying @otmezger's iOS10 changes to a local copy of this repo, hopefully will start testing that within the next couple of days. I have practically no iOS dev experience myself, but it seems fairly straightforward.

If that works out fine I'll see if I can submit a PR for @taivo

**Comment by taivo** [comment] 2017-01-10 03:55
Thank you so much @pocketninja. 

To everyone else, sorry I haven't had a chance to work on this. Moved to a new city, started a new job, and looking for an apartment so no time available. 

Will definitely merge the promised pr to modernize this plugin. 

Thanks!

**Comment by taivo** [comment] 2017-01-11 07:40
@pocketninja 's PR #87 is merged. Please help yourself to the new update. Thanks also to @otmezger , whose code was used to create the PR.

**Closed by taivo** 2017-01-11 07:40 UTC

**Comment by budda** [comment] 2017-01-13 22:36
@cybeerboy so are you all up and working with deviceToken registered and 1.0.7 of this plugin? If you are -- mind sharing the secret as I can't get it working! :-(

**Comment by DanIugo** [comment] 2017-01-15 22:32
The devices I've tested on have been registering device tokens - iOS 9, 10, and 10.2. 

These have been fresh installs however - perhaps a parse installation caches a device token (incl empty ones?) and needs cache/data cleared or an uninstall first?

Any devices which already had a device token (from when it didn't have iOS 10) kept their device token as far as I could tell.

**Comment by budda** [comment] 2017-01-16 09:59
@DanIugo thanks. Managed to solve it on the weekend in #88 with the missing capability switched on in XCode!

@DanIugo Are you available by some means for a quick (hopefully) chat about iOS 10 and receiving push notifications ?

**Comment by DanIugo** [comment] 2017-01-16 22:39
@budda - sure, have you got some means to contact you? I'm not keen to drop my email address publicly and can't seem to follow any other messaging methods either (can't DM your account on Twitter/etc)

Is it an issue in particular? For reference, I am not an iOS developer at all so there is a good chance I can't assist. For this issue I essentially migrated code that otmezger had already written.

**Comment by budda** [comment] 2017-01-16 23:01
@DanIugo i've activated allowing direct messages from anybody on Twitter now. Issue is the iOS Cordova app not receiving any notifications sent from the Parse dashboard since changing to this new plugin.

**Comment by DanIugo** [comment] 2017-01-17 23:25
Have had a quick chat with @budda, sounds like the ball is rolling there now. 👍 

In case others have issues with iOS apps not receiving notifications here are some things to check:

- Check app capabilities in Xcode, Push Notifications needs to be enabled if it is not
- Check your Developer and Distributor provisioning profiles
- Check your PN certificates, ensure they are valid and haven't expired
- Check you have the correct PN certificate configured in Parse

I've had to recreate certificates/provisioning profiles a couple times over the last year because existing (and apparently valid) ones weren't working.
