### ISSUE TITLE
Installation not saving?

### ISSUE THREAD

**Issue by andrescruz** [taivo/parse-push-plugin#52] opened 2016-07-09 18:01 UTC
I'm getting the following error after running the subscribe function
[Error]: unauthorized (Code: 0, Version: 1.13.0)

When I run the ParsePushPlugin.getInstallationObjectId() function, I receive a null value which makes me believe that it's not saving the installation. 

Any idea how I can resolve this or what I should be looking into?

**Comment by taivo** [comment] 2016-07-09 20:34
Which platform is this happening on and are you able to verify in the database that an installation has not been saved?

**Comment by andrescruz** [comment] 2016-07-09 21:03
It's happening on an ionic app for iOS. And yes I can confirm that the installation is not saving the new row.

**Comment by mymanga** [comment] 2016-07-11 05:41
Same here, followed all instructions. new installation not being saved. Running ionic1 app

**Comment by andrescruz** [comment] 2016-07-11 15:17
I'm on Ionic v 1.3 as well using back4app.com services for Parse. I've gone through the steps and recreated the certificates and provisioning profiles multiple times.

**Comment by taivo** [comment] 2016-07-11 23:10
Looks like a recent commit may have been the cause. For now, can you try one of 2 things?

1. roll back and use an older commit of this plugin b7af55f1810f6492c879a899e2d8e527509f844b
2. in your config.xml, add `<preference name="ParseAutoRegistration" value="true" />`

Let me know if that works. I'm a bit swamped right now but will get a permanent solution out next week or so.

**Comment by mymanga** [comment] 2016-07-12 00:46
How to "roll back" Im a beginner at git

**Comment by andrescruz** [comment] 2016-07-12 16:09
you roll back by
`cordova plugin add https://github.com/taivo/parse-push-plugin#b7af55f1810f6492c879a899e2d8e527509f844b `

@taivo I attempted both and neither solution worked for me. I can wait it out and see if you're able to get this resolved soon. Thanks!

**Comment by cleever** [comment] 2016-07-27 03:54
Same issue here.

**Comment by movibe** [comment] 2016-07-29 04:38
same problem , someone has managed to turn the ionic v1 ?

**Comment by taivo** [comment] 2016-07-29 08:11
I was not able to replicate this problem with the included example app. I did some rewrite though to make the device registration + installation saving steps more robust. Please try the latest commit.

If the problem persists, I'm going to need some logs from you guys.

**Comment by movibe** [comment] 2016-07-29 10:54
Hi @taivo , thanks for the answer, I will be creating another ionic application for testing and make the maximum possible debug and share github source code and access to the server to assist in the contribution of this solution

**Comment by taivo** [comment] 2016-07-29 18:30
Thank you @movibe. If you want, this repo has an `example` directory. There are code and docs in that directory to help you quickly rig up a test app. Javascript handlers for push notifications are also included. That app can be a good template to start if you want to save some time.

**Comment by cleever** [comment] 2016-08-01 15:05
When I run:

```
 ParsePushPlugin.getInstallationId(function(id) {
         // note that the javascript client has its own installation id,
         // which is different from the device installation id.
          alert("device installationId: " + id);
      }, function(e) {
          alert('error');
      });
```

The alert dialog shows the installationId correctly. However nothing is saved to Installation table in my Parse Server.

**Comment by cleever** [comment] 2016-08-01 20:15
adb logcat noticeable output:

```
W/System(26686): Ignoring header X-Parse-Client-Key because its value was null.


E/com.parse.ManifestInfo(25598): 
Cannot use GCM for push because the app manifest is missing some required declarations. 
Please make sure that these permissions are declared as children of the root <manifest> element:

08-01 17:03:31.158: E/com.parse.PushService(31115): Tried to use push, but this app is not configured for push due to: Push is not configured for this app because the app manifest is missing required declarations. 
Please add the following declarations to your app manifest to support either GCM or PPNS for push (or both). To enable GCM support, please make sure that these permissions are declared as children of the root <manifest> element:

08-01 17:03:30.869: I/ActivityManager(1854): Start proc 31115:com.limbic.towermadness2/u0a250 for broadcast com.limbic.towermadness2/com.parse.ParseBroadcastReceiver
08-01 17:03:31.156: E/com.parse.ManifestInfo(31115): <service android:name="com.parse.PushService" />
08-01 17:03:31.156: E/com.parse.ManifestInfo(31115): <receiver android:name="com.parse.GcmBroadcastReceiver" android:permission="com.google.android.c2dm.permission.SEND">
08-01 17:03:31.158: E/com.parse.PushService(31115): <service android:name="com.parse.PushService" />
08-01 17:03:31.158: E/com.parse.PushService(31115): <receiver android:name="com.parse.GcmBroadcastReceiver" android:permission="com.google.android.c2dm.permission.SEND">
08-01 17:03:31.158: E/com.parse.PushService(31115): <service android:name="com.parse.PushService" />
08-01 17:03:31.158: E/com.parse.PushService(31115): <receiver android:name="com.parse.ParseBroadcastReceiver">
08-01 17:03:31.296: I/ActivityManager(1854): Start proc 31138:com.basf.suvinil/u0a215 for broadcast com.basf.suvinil/com.parse.ParseBroadcastReceiver
08-01 17:03:38.394: V/AlarmManager(1854): sending alarm {1cb5405 type 2 *walarm*:com.parse.RetryGcmRegistration}
08-01 17:03:38.410: V/AlarmManager(1854): done {1cb5405, *walarm*:com.parse.RetryGcmRegistration} [16ms]
08-01 17:04:00.873: V/AlarmManager(1854): sending alarm {1cb5405 type 2 *walarm*:com.parse.RetryGcmRegistration}
08-01 17:04:00.893: V/AlarmManager(1854): done {1cb5405, *walarm*:com.parse.RetryGcmRegistration} [20ms]
08-01 17:04:01.976: I/ActivityManager(1854): Start proc 31388:com.cleanup.cleanupapp/u0a311 for broadcast com.cleanup.cleanupapp/com.parse.GcmBroadcastReceiver

```


AndroidManifest.xml

```
<?xml version='1.0' encoding='utf-8'?>
<manifest android:hardwareAccelerated="true" android:versionCode="900" android:versionName="0.0.1" package="com.ionic.ionicapp" xmlns:android="http://schemas.android.com/apk/res/android">
    <supports-screens android:anyDensity="true" android:largeScreens="true" android:normalScreens="true" android:resizeable="true" android:smallScreens="true" android:xlargeScreens="true" />
    <application android:hardwareAccelerated="true" android:icon="@drawable/icon" android:label="@string/app_name" android:name="github.taivo.parsepushplugin.ParsePushApplication" android:supportsRtl="true">
        <activity android:configChanges="orientation|keyboardHidden|keyboard|screenSize|locale" android:label="@string/activity_name" android:launchMode="singleTop" android:name="MainActivity" android:screenOrientation="portrait" android:theme="@android:style/Theme.Black.NoTitleBar" android:windowSoftInputMode="adjustResize">
            <intent-filter android:label="@string/launcher_name">
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>
        <service android:name="com.parse.PushService" />
        <receiver android:exported="false" android:name="github.taivo.parsepushplugin.ParsePushPluginReceiver">
            <intent-filter>
                <action android:name="com.parse.push.intent.RECEIVE" />
                <action android:name="com.parse.push.intent.DELETE" />
                <action android:name="com.parse.push.intent.OPEN" />
            </intent-filter>
        </receiver>
        <receiver android:name="com.parse.GcmBroadcastReceiver" android:permission="com.google.android.c2dm.permission.SEND">
            <intent-filter>
                <action android:name="com.google.android.c2dm.intent.RECEIVE" />
                <action android:name="com.google.android.c2dm.intent.REGISTRATION" />
                <category android:name="com.ionic.ionicapp" />
            </intent-filter>
        </receiver>
        <meta-data android:name="com.parse.push.gcm_sender_id" android:value="id:CORRECT_GCM" />
    </application>
    (...)
</manifest>

```

**Comment by taivo** [comment] 2016-08-02 09:39
ParsePushPlugin.getInstallationId() itself does not save the installation id to the database. It merely reads the id generated by Parse client sdk.

Thanks for the log and manifest. I'm reviewing them now.

**Comment by taivo** [comment] 2016-08-02 10:16
Hi @cleever, regarding this line in the manifest: 

`<meta-data android:name="com.parse.push.gcm_sender_id" android:value="id:CORRECT_GCM" />`

Did you edit the id out for privacy reason? Or was the config.xml preference `ParseGcmSenderId` mistakenly set as "CORRECT_GCM"

**Comment by cleever** [comment] 2016-08-02 11:18
Hello @taivo.
Thank you for your support.
I've edited the id for privacy reason.

**Comment by movibe** [comment] 2016-08-02 12:06
Hello @taivo , plugin worked perfectly, what I noticed is that needs to verify the config.xml file with the example you put

**Comment by taivo** [comment] 2016-08-02 13:20
Hi @movibe. You are welcome!

Can you share with us what led to the original problem? Also, was your issue on ios or android?

**Comment by taivo** [comment] 2016-08-02 13:26
@cleever, can you do me a favor and try to replicate this problem with the included test app in the 'example' directory? View that directory on github and you will see instructions to build that app

**Comment by cleever** [comment] 2016-08-02 13:52
@taivo the example app works perfectly with the example server.
The problem is that my server requires a client key.

For now my issue is resolved by the changes introduced in the following pull request:
https://github.com/taivo/parse-push-plugin/pull/57

The installation is finally saved and push notification is being delivered.

Thank you again.

**Comment by jimcamut** [comment] 2016-08-02 14:40
What's the process for saving a new installation to the database? Will `ParsePushPlugin.register(successCB, errorCB)` handle that?

**Comment by cleever** [comment] 2016-08-02 14:56
@jimcamut 

The process of saving is made automatically by the plugin.

But you could disable the auto saving and use ParsePushPlugin.register. But only in IOS.
https://github.com/taivo/parse-push-plugin#ios

**Comment by jimcamut** [comment] 2016-08-02 15:02
@cleever I'm testing with legacy Parse.com server and having the same issue that you mentioned. There are not any installations saved when I run the plugin, although everything appears to be working. I'm going to try your commit `f83b8e2e6ad9aebe96675623b50137011c21a77e` and see if it works.

**Comment by cleever** [comment] 2016-08-02 16:08
@jimcamut Only one tip:

You should you use a Client_Key not JavaScript_Key.

**Comment by jimcamut** [comment] 2016-08-02 16:26
^^ @cleever that was my issue all along. I didn't have the correct client key. It's working now - thanks for the help!

**Comment by taivo** [comment] 2016-08-02 18:22
> @cleever: the example app works perfectly with the example server.
> The problem is that my server requires a client key.

Then it cannot be clearer that your PR is needed. This is the usecase that I was looking for. Thanks for your input.

Also, since it seems there is some confusion regarding javascript key vs client key, I will update the troubleshooting section of the docs to say that. This has been a very good thread.

**Comment by taivo** [comment] 2016-08-02 20:47
@andrescruz , @mymanga , and other folks with the original iOS issue, are you still having problem with installation not being saved automatically?

**Comment by taivo** [comment] 2016-08-02 21:35
Those of you with some expertise in Cordova Windows and WinJS, would you kindly look at issue #42 for me? Sorry for the sidetrack. I'm currently unable to move pass that issue to offer support for Windows. Many thanks.

**Closed** 2016-08-12 20:49 UTC

**Comment by stevenballs** [comment] 2017-09-19 09:32
How to use Parse push notification with ionic 2 and ionic 3

1.You Create new project.
Command>ionic start <nameproject> <type> --v2

2.You open file config.xml in new project.
<preference name="ParseAppId" value="APPLICATION_ID" />
    
<preference name="ParseServerUrl" value="http://notification.apps.thaibev.com/parse/" />
    
<preference name="ParseGcmSenderId" value="579647902421" />
    
<preference name="ParseMultiNotifications" value="true" />
    
<preference name="ParseAutoRegistration" value="false" />
    
<preference name="ParseNotificationIcon" value="icon" />

3.You add parse-push-plugin plugin.
Command>cordova plugin add https://github.com/taivo/parse-push-plugin --save

4.You Open app.component.ts file  form src/app/app.component.ts
4.1 You add variable > declare var ParsePushPlugin: any;
4.2 You new function in constractor in file app.component.ts
ParsePushPlugin.getInstallationId(function (id) {
	ParsePushPlugin.on('receivePN', function (pn) {
		alert(pn.alert);
	});
});
