### ISSUE TITLE
Update to work with open source server

### ISSUE THREAD

**Issue by campers** [taivo/parse-push-plugin#37] opened 2016-05-20 14:18 UTC
Hello, I've started looking into updating the plugin to work with the open source server using the latest Android SDK, so I wanted to put my notes here so whether myself or someone else has the time next to take the next steps or either platform.

The server side config docs is at https://github.com/ParsePlatform/parse-server/wiki/Push but we're more interested in the client app config at https://github.com/ParsePlatform/Parse-Server/wiki/Push-Configuring-Clients
Both the SDK's need to be updated the latest versions.

In my custom Android Application in onCreate() I've updated the Parse.initialise() call to

        Parse.initialize(new Parse.Configuration.Builder(this)
            .applicationId("@@parseAppId")
            .clientKey(null)
            .server("@@parseServerUrl") // The trailing slash is important.
            .build()
        );

I have a gulp script which replaces the @@parseAppId and @@parseServerUrl placeholders from config values before copying it to /platforms/android/src/org/apache/cordova/CustomApplication.java
(I'm building a Cordova application so I have to generate this file in the Android project)

It appears there's another configuration step as we need to use our own GCM ids. I think this should able to be configured by a variable when installing the plugin.
```
<!-- IMPORTANT: Change "YOUR_SENDER_ID" to your GCM Sender Id. -->
<meta-data android:name="com.parse.push.gcm_sender_id"
  android:value="id:YOUR_SENDER_ID" />;
```

I've done very little native iOS, I noticed this commit added the serverUrl variables which would need to configured
https://github.com/ParsePlatform/Parse-SDK-iOS-OSX/commit/4b67292905b56848959b0746b90eb8db4beb0a23

**Comment by taivo** [comment] 2016-05-22 07:58
@campers thank you for looking into this and posting a report. I will start on the ios side in a few days and update you as well

**Comment by campers** [comment] 2016-05-24 15:59
Pull request #39 is in the works for Android

**Comment by fmendoza** [comment] 2016-05-25 17:10
Hi, if you need help with the testing please let me know.

**Comment by taivo** [comment] 2016-05-25 22:42
Will definitely take you up on that offer :)

**Comment by fmendoza** [comment] 2016-05-25 22:47
Please tell how to test @campers code

**Comment by taivo** [comment] 2016-05-27 09:49
We now have a separate branch `oss-parse-server` to contain the work in progress for the time being. Changes by @campers are for Android and are mentioned in the docs.

I've also made update to the iOS side and it works on my iPhone. Turns out required changes to the plugin is very minor. Most of the difference is in server configuration, which I addressed in the docs.

As for Android, I think we may want to delegate GCM_SENDER_ID setup to server configuration and explain it in the docs instead of requiring it as a plugin variable. This would make it consistent with the way `Parse.Push` has been working, i.e., the server does the actual pushing to GCM and APNS so only the server needs to know things like sender id and push certificates. At least that's my take for now. I'll get  a hold of an Android phone this weekend to see if that's the right thing to do.

@fmendoza, significant changes are still happening to the code so let's hold off on testing till next week. I don't want to waste your valuable testing offer on intermediate code :)

**Comment by campers** [comment] 2016-05-27 16:26
I wasn't sure if the GCM_SENDER_ID was required to register which sender you want to receive from.  I'm ok with not supporting client side push notification. Will have to see what happens in testing.

**Comment by ihomecall** [comment] 2016-05-29 20:06
I am trying to use this plugin for  third-party parse server (back4app.com).
But has issue to saving the PFInstallation object to the back4app server. It seems it still tries to save to parse.com server.    Do anybody know where should I modify to direct the parse initialize to back4app server? 

is it in the Parse.Framework?  if so where do I get the source code of Parse.Framework, modify the serverURL and compile it into package?

**Comment by campers** [comment] 2016-05-30 02:36
You need to install from the oss-parse-server branch https://github.com/taivo/parse-push-plugin/tree/oss-parse-server to be able to configure the serverURL in the plugin

**Comment by taivo** [comment] 2016-06-02 01:43
Hi @campers, you're right. The client app has to know GCM_SENDER_ID for registration. 

I was hoping to make that variable optional so we can merge oss-parse-server back into the master branch and have the same branch working for both parse.com and its open source version. I don't see any clean and simple way to do that though. I guess the 2 branch system is here to stay until 01/2017 when Parse.com goes down. Any thoughts on this?

**Comment by taivo** [comment] 2016-06-02 01:44
Hi @fmendoza , care to give the oss-parse-server branch a spin? Both Android and iOS are there. Let us know how it goes. Thanks.

**Comment by fmendoza** [comment] 2016-06-02 01:54
Yes. I'll do the testing tomorrow and get back to you asap.

**Comment by campers** [comment] 2016-06-02 13:32
@taivo they are recommending moving apps off by the end of the July https://parse.com/migration

The current release is sufficient for those still on the managed service. Going forward its all about Parse as a framework, so if it was me I'd just move ahead and update the doco to say if you still need to pull the older version for managed Parse then they can use the current version head commit. i.e.

cordova plugin add https://github.com/taivo/parse-push-plugin#f33a844c44118b5f714890fae54ffd04dc6d2f1e

How about publishing the next release of plugin to npm? cordova-parse-push is available

**Comment by taivo** [comment] 2016-06-02 22:04
Those are excellent suggestions, @campers. I'll wait a few more days to see if any strange issue turns up in testing. Will do what you suggest this weekend or early next week.

**Comment by fmendoza** [comment] 2016-06-07 15:41
I tested @campers code and it's working fine so far. Once the app is launched, the Installation object is saved correctly in database. I tested in my local environment and Heroku + mLab. Now I'm having some issues sending push notifications, but it seems that it's a problem in server side.

Thanks for your hard work.

**Comment by taivo** [comment] 2016-06-08 02:07
Thank you both for pitching in. That gave me a bit more motivation to revisit this repo :)

I've moved the old master branch to a branch called `parse-com` and merge `oss-parse-server` into the master branch. Docs have also been updated to let people know which branch to use.

I'm closing this thread, but hope to run into you guys again on this project or in the wider open source world.

**Closed by taivo** 2016-06-08 02:07 UTC

**Comment by campers** [comment] 2016-06-08 12:33
Happy to have helped. I made my own fork a while back for my project with a couple of fixes, but looked for the best fork so far to contribute this to, so thanks for what you'd already done.

**Comment by fmendoza** [comment] 2016-06-18 19:01
Hi

I discovered a little issue on Android. 

When the app is completely close I'm not receiving push notifications. If the app is in background everything work as expected.

**Comment by fmendoza** [comment] 2016-06-18 19:06
Also I created a fork using gradle instead of jar files. Any chance to integrate the changes to this repo?

https://github.com/fmendoza/parse-push-plugin

**Comment by taivo** [comment] 2016-06-18 22:27
@fmendoza, are you saying `openPN` is not being triggered on true cold start? If not, please elaborate. I'm very interested in getting this right. If it's an `openPN` cold start problem, there are 2 things you can do:

1. Try setting up your `openPN` handler even earlier in the init flow, i.e., something that occurs earlier than $ionicPlatform.ready(), maybe deviceready. The problem could be because the handler is setup after `openPN` was triggered.
2. Try the ionic-testpn app in the example dir to see if the problem still occurs.

Let me know your findings.

Regarding the gradle fork, sounds like a good thing. Please create a pr and I'll have a look.

**Comment by fmendoza** [comment] 2016-06-18 22:39
I mean if the app is not running I don't get the notification (at least I don't see the notification in status bar. However if the app is running (foreground or background) I get the notification without problem.

I would try your suggestion and try the app example.

**Comment by fmendoza** [comment] 2016-06-19 01:36
Also everytime I build the app I'm receiving the following error:


`Element meta-data#com.parse.push.gcm_sender_id at AndroidManifest.xml:33:9-113 duplicated with element declared at AndroidManifest.xml:32:9-98`

Inspecting AndroidManifest.xml I notice the duplicated tag

```
<meta-data android:name="com.parse.push.gcm_sender_id" android:value="id:135228772521" />
<meta-data android:name="com.parse.push.gcm_sender_id" android:value="id:CONFIG_XML_ParseGcmSenderId" />
```

**Comment by taivo** [comment] 2016-06-20 03:48
Ah, I know exactly what went wrong. I'll check in a fix tomorrow when I get a chance. In the mean time the way to fix it is to uninstall the plugin, then go into your AndroidManifest and completely remove whatever '<meta-data android:name="com.parse.push.gcm_sender_id" android:value="id:FOO" />' that's left and reinstall the plugin.

Were you able to replicate your cold start problem with the example ionic-testpn app?

**Comment by fmendoza** [comment] 2016-06-20 19:02
Yes same problem with the example project. I don't get the notification if the app is completely closed.

**Comment by taivo** [comment] 2016-06-20 19:17
Which android version are you using?

Also, regarding the `meta-data#com.parse.push.gcm_sender_id` issue, I've updated the uninstallation script to purge all those meta tags. Just  remove then add the plugin again and you're good to go.

**Comment by taivo** [comment] 2016-06-20 23:29
Ok then I'm sorta stumped. I have a nexus 4 with Android 5.1.1 here and it's receiving notifications in the tray just fine after I swiped ionic-testpn off the app stack.

Can you check your logcat for entries that happen around the time your phone should be receiving the pn? Maybe some exception was thrown.

**Comment by fmendoza** [comment] 2016-06-21 00:00
I saw the message below on logcat

`broadcast intent callback: result=CANCELLED forIntent { act=com.google.android.c2dm.intent.RECEIVE pkg=com.taivo.testpn (has extras) }

**Comment by taivo** [comment] 2016-06-21 22:57
After some research, I found [this explanation](http://stackoverflow.com/questions/18196863/broadcast-intent-cancelled-android-gcm) to be the most likely candidate. That fix is checked in so cross your fingers and try it out :)

**Comment by taivo** [comment] 2016-06-22 01:50
There was another source of error for the duplicate `meta-data` issue. I just fixed it in the latest commit d31a3a2f2da8f0dbe9c02ee0e869a7e34f514f83

**Comment by fmendoza** [comment] 2016-06-22 03:00
I just tried your latest changes and push still don't work when the app is completely closed. I don't know what is the problem but I'll do my best to help you find a proper solution.

**Comment by taivo** [comment] 2016-06-22 03:33
Ok sounds good. Thank you. Without being able to replicate the problem, I'm not able to do much to solve it. The java code is actually pretty simple if you want to take a crack at this. I suggest starting with `ParsePushPluginReceiver.onPushReceive`. It's the function that decides whether to call javascript or create a tray notification.

If I think of any possible solution, you'll be the first to know.

**Comment by taivo** [comment] 2016-06-24 06:47
I found another potential fix. But first, I want to clarify that when you say "the app is completely closed", you meant that you swiped it off the app stack. The app was not "force closed", right? For force closed app, the intended behavior is not accepting any more notification so what you have been observing would be correct behavior and we should just roll back my attempts at solving this problem.

That said, now assuming your apps were only swiped off the stack. Try the latest commit b5d08e9f23affd394d006e83aa75686000466a6f, it's based on a solution [here](https://github.com/phonegap/phonegap-plugin-push/issues/211) by @vikasing . Let me know if it works.

**Comment by fmendoza** [comment] 2016-06-24 16:33
Yes I only swiped off from the app stack. I tested your latest commit and I had no luck :(
