### ISSUE TITLE
receivePN not work

### ISSUE THREAD

**Issue by nguyenphucthanh** [taivo/parse-push-plugin#90] opened 2017-01-16 09:55 UTC
hi.

I'm using Parse on Nodechef. I configured everything OK as documented. Push Notification works. But I cannot catch notification in receivePN callback (on iOS) and on android, catched notification is an empty string.

Do you have any idea? openPN doesn't fire too.

Thanks!

**Comment by tomazhawkjr** [comment] 2017-01-16 13:49
I have same problem.

**Comment by tomazhawkjr** [comment] 2017-01-16 18:33
I downgrade cordova to 6.1.1 and plugin to b7af55f, problem solved.

**Comment by nguyenphucthanh** [comment] 2017-01-17 06:43
@tomazhawkjr I tried that solution but still not working.

**Comment by taivo** [comment] 2017-01-17 06:49
Did you wrap the .on('receivePN') call with some sorr of document ready event handler?

**Comment by nguyenphucthanh** [comment] 2017-01-17 06:52
@taivo yes I ready did it.

FYI, this function in xCode cannot fire:

- (void)swizzled_application:(UIApplication *)application didReceiveRemoteNotification:(NSDictionary *)userInfo

`
$ionicPlatform.ready(function() {
ParsePushPlugin.on('receivePN', function(pn){
    console.log('yo i got this push notification:' + JSON.stringify(pn));
});

ParsePushPlugin.on('openPN', function(pn){
    console.log('The user opened a notification:' + JSON.stringify(pn));
});
});
`

**Comment by tomazhawkjr** [comment] 2017-01-17 14:39
@nguyenphucthanh, you try ionic state reset after downgrade?

**Comment by nguyenphucthanh** [comment] 2017-01-17 17:11
@tomazhawkjr I have tried as you told but no luck.

**Comment by taivo** [comment] 2017-01-18 06:59
@nguyenphucthanh you mentioned that push notification worked but you couldnt catch receivePN. How did you know push notif work? Via device log? Can you elaborate on this?

**Comment by nguyenphucthanh** [comment] 2017-01-19 11:18
hi @taivo , my team detected problem of iOS. The payload should include "content-available" : 1 

we are debugging android why it comes but js "catch" only empty string instead of an object.

```
var pushParams = {
   where: self.getQueryByTarget(params.target),
   data: {
    action: self.Action,
    alert: params.text,
    data: params.data,
                "content-available": 1,
    sound: "default"
   }
  };
```

**Comment by adjmb** [comment] 2017-01-19 16:00
@nguyenphucthanh For the Android empty string. I changed this part in the jsCallback method of the Class ParsePushPlugin.java

*helperpause is a boolean that changes when the app becomes in pause.

```
public static void jsCallback(JSONObject _json, String pushAction){
      List<PluginResult> cbParams = new ArrayList<PluginResult>();
    	cbParams.add(new PluginResult(PluginResult.Status.OK, _json));
    	cbParams.add(new PluginResult(PluginResult.Status.OK, pushAction));
		//avoid blank
		PluginResult dataResult;
		if (pushAction.equals("OPEN")) {
			if (helperPause)
				dataResult = new PluginResult(PluginResult.Status.OK, _json);
			else
				dataResult = new PluginResult(PluginResult.Status.OK, cbParams);
		} else {
			dataResult = new PluginResult(PluginResult.Status.OK, _json); 
		}
	  dataResult.setKeepCallback(true);


      if(gEventCallback != null){
         gEventCallback.sendPluginResult(dataResult);
      } else{
         //
         // save the incoming push payloads until gEventCallback is ready.
         // put a sensible limit on how queue size;
         if(pnQueue.size() < 10){
            //pnQueue.add(new PNQueueItem(_json, pushAction));
            pnQueue.add(dataResult);
         }
      }
   }
```

I explored this issue and the problem is that Cordova is trying to pass a ArrayList (Java) to JSON (Javascript) and there are not compatible. So, I just pass the payload directly. Hopefully, it works.

**Comment by nguyenphucthanh** [comment] 2017-01-20 03:18
@adjmb hi your code works perfectly, just one problem, because I'm JS developer and I don't know how to work with your "helperPause", so I remove all conditions and only keep this:

```
dataResult = new PluginResult(PluginResult.Status.OK, _json);
```

Thanks for your help!!!

**Comment by nguyenphucthanh** [comment] 2017-01-20 03:19
@taivo I think you should add a note for developer about "content-available" in push notification payload.

Thanks

**Comment by adjmb** [comment] 2017-01-20 08:14
@nguyenphucthanh. Initially, I have it as you did. The problem is when you receive the notification back, it always be received by "receivePN" and never with "openPN". If you want to distinguish them. This is helperpause (sorry for not sharing before). 

``
private static boolean helperPause = false;

@Override
   public void onPause(boolean multitasking) {
      super.onPause(multitasking);
      gForeground = false;
	  helperPause = true;
   }

@Override
   public void onDestroy() {
      gWebView = null;
    	gForeground = false;
		helperPause = false;
    	super.onDestroy();
   }

**Comment by tomazhawkjr** [comment] 2017-01-23 19:43
@nguyenphucthanh and @adjmb, wich version of cordova are you guys using? I still can't solve my problem with push notifications when the app is closed. It worked some times but have no idea why it's a pain in the ass to debug using safari web inspector. Sometimes it enters the receivedPN and sometimes it does not.

**Comment by nguyenphucthanh** [comment] 2017-01-24 02:38
@tomazhawkjr , @adjmb 

for iOS, I didn't edit anything but for android, first, I return the _json directly in PluginResult instead of the cbParams

```
  PluginResult dataResult;
  if (pushAction.equals("OPEN")) {
    try {
      _json.put("OPEN", true); // a little hack because JS cannot read cbParams correctly
    } catch (JSONException e) {
      e.printStackTrace();
    }
  }
  dataResult = new PluginResult(PluginResult.Status.OK, _json);
```

then in ParsePushPlugin.json

```
if(pushAction === 'OPEN' || pn.OPEN){
				//
				// trigger a callback when user click open a notification.
				// One usecase for this pertains a cordova app that is already running in the background.
				// Relaying a push OPEN action, allows the app to resume and use javascript to navigate
				// to a different screen.
				//
            ParsePushPlugin.softTrigger(ParsePushPlugin._openEvent, pn);
			}
```

**Comment by tomazhawkjr** [comment] 2017-01-25 11:47
I still can't manage to make the push notification work properly. It sometimes doesn't even trigger the 'receivedPN' function, even if I put it inside the 'on ready' of ionic. I get the notification, but when I click it, it doesn't trigger the function.

My Android version works fine, my problem is just with the iOS version, and I don't know a thing of Obj-C to try modifying things on the plugin source code

**Comment by adjmb** [comment] 2017-02-08 08:09
@tomazhawkjr, see the solution of @avilasolucoes-naora. It's solution is working smoothly in Android. The issue about  "I get the notification, but when I click it, it doesn't trigger the function." is fixed in his/her/their last release

**Comment by avilasolucoes-naora** [comment] 2017-02-08 13:40
Thanks @adjmb,  @avilasolucoes-naora is the repository from my job, I work in last release from it, grouping suggested solutions for you and @nguyenphucthanh. The plugin yet not works on android lollipop when the app is closed.

**Comment by adjmb** [comment] 2017-02-10 00:34
Hey Guys. @tomazhawkjr, @avilasolucoes-naora, @nguyenphucthanh ,
I have a question for all of you. 
Does the plugin work for you in IOS 10 when the app is the background, but not in front?  I receive the notification in the tray, but no events are triggered in the javascript. 

In other words, I got the plugin to work as following:
- working now in Android 4.4.2, Android 6 when the app is Closed, Background & Foreground.
- working now in IOS 10 when the app is Closed & Foreground.

**Comment by nguyenphucthanh** [comment] 2017-02-10 03:24
@adjmb for me it works in background mode on iOS10

**Comment by adjmb** [comment] 2017-02-10 05:16
@nguyenphucthanh thanks for your answer. Beside the `"content-available" : 1` in the payload, did you make any other change to the last commit by taivo?

**Comment by nguyenphucthanh** [comment] 2017-02-10 06:59
@adjmb this is all I did in previous comment https://github.com/taivo/parse-push-plugin/issues/90#issuecomment-274684768

**Comment by tomazhawkjr** [comment] 2017-02-10 14:58
@adjmb, for IOS I needed set `_coldStartDelayMs=1000 ` in parse-push-plugin.js, and modify @nguyenphucthanh  recommendation `if(pushAction === 'OPEN' || pn.OPEN){`

but I did not test much.

**Comment by adjmb** [comment] 2017-02-10 17:16
@nguyenphucthanh @tomazhawkjr thanks for your response. 
I have implemented both things, but they're not working for background mode in IOS 10. I ended simulating the notification through firebase (FOREGROUND & BACKGROUND).  I know JAVA and JAVASCRIPT, but I don't know much Objective C. 

Thank you, though.

**Comment by avilasolucoes-naora** [comment] 2017-02-10 19:55
The problem is because the push event is triggered before the openPN is registered. On Xcode click "Window->Devices->MyIphone" and test, you will see. Not is triggered because not is registered.

**Closed** 2017-03-20 23:29 UTC
