### ISSUE TITLE
Installation not saving--404

### ISSUE THREAD

**Issue by dhealy05** [taivo/parse-push-plugin#65] opened 2016-09-02 04:09 UTC
No installations are being saved to my database--I get the following error message on Heroku when opening the app:

2016-09-02T04:01:23.401519+00:00 heroku[router]: at=info method=POST path="/classes/_Installation" host=redacted.herokuapp.com request_id=e7153e75-299e-415b-b7ca-90911f9634e6 fwd="69.127.212.147" dyno=web.1 connect=0ms service=2ms status=404 bytes=233

I've tried the solution offered in #52 to roll back to an earlier version, and add <preference name="ParseAutoRegistration" value="true" /> in my config.xml. No luck--I also tried setting the value to false, and calling register. I got the same error.

I don't think the issue is not my server configuration for Installations--I save, edit channels, etc. in my iOS client with no errors. 

Any tips? Thanks!

**Comment by taivo** [comment] 2016-09-02 07:16
"in my iOS client with no errors"

I'm not sure if you mean this plugin works fine for iOS. In case it's an Android problem, please check the android manifest's `application` tag for the `android:name` parameter as mentioned in my last post on issue #55?

If this happens on iOS, let me know. I have a few ideas to try.

**Comment by dhealy05** [comment] 2016-09-02 10:24
Sorry I wasn't clear--I use the iOS SDK, not Ionic, for iOS. No issues saving Installations to my server there.

The application tag seems to be correct--including the AndroidManifest.xml in full here:

<?xml version='1.0' encoding='utf-8'?>
<manifest android:hardwareAccelerated="true" android:versionCode="101018" android:versionName="1.1.0" package="com.redacted.redacted" xmlns:android="http://schemas.android.com/apk/res/android">
    <supports-screens android:anyDensity="true" android:largeScreens="true" android:normalScreens="true" android:resizeable="true" android:smallScreens="true" android:xlargeScreens="true" />
    <uses-permission android:name="android.permission.INTERNET" />
    <application android:hardwareAccelerated="true" android:icon="@drawable/icon" android:label="@string/app_name" android:name="github.taivo.parsepushplugin.ParsePushApplication" android:supportsRtl="true">
        <activity android:configChanges="orientation|keyboardHidden|keyboard|screenSize|locale" android:label="@string/activity_name" android:launchMode="singleTop" android:name="MainActivity" android:screenOrientation="portrait" android:theme="@android:style/Theme.DeviceDefault.NoActionBar" android:windowSoftInputMode="adjustResize">
            <intent-filter android:label="@string/launcher_name">
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>
        <service android:name="com.parse.PushService" />
        <receiver android:exported="false" android:name="github.taivo.parsepushplugin.ParsePushPluginReceiver">
            <intent-filter>
                <action android:name="com.parse.push.intent.RECEIVE" />
                <action android:name="com.parse.push.intent.DELETE" />
                <action android:name="com.parse.push.intent.OPEN" />
            </intent-filter>
        </receiver>
        <receiver android:name="com.parse.GcmBroadcastReceiver" android:permission="com.google.android.c2dm.permission.SEND">
            <intent-filter>
                <action android:name="com.google.android.c2dm.intent.RECEIVE" />
                <action android:name="com.google.android.c2dm.intent.REGISTRATION" />
                <category android:name="${applicationId}" />
            </intent-filter>
        </receiver>
        <meta-data android:name="com.parse.push.gcm_sender_id" android:value="id:redacted" />
    </application>
    <uses-sdk android:minSdkVersion="16" android:targetSdkVersion="23" />
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
    <uses-permission android:name="android.permission.WAKE_LOCK" />
    <uses-permission android:name="android.permission.VIBRATE" />
    <uses-permission android:name="com.google.android.c2dm.permission.RECEIVE" />
    <permission android:name="${applicationId}.permission.C2D_MESSAGE" android:protectionLevel="signature" />
    <uses-permission android:name="${applicationId}.permission.C2D_MESSAGE" />
</manifest>

**Comment by dhealy05** [comment] 2016-09-06 20:17
after some uninstalling and reinstalling its saving. thanks!

**Comment by taivo** [comment] 2016-09-06 22:38
This remove then readd the plugin for it to work has been reported a few times. I really hope to understand the root cause and fix the annoyance but I don't have enough data points yet. 

If you have an idea regarding what might have caused the problem, please let me know here.

Thank you for letting me know your findings.

**Comment by dhealy05** [comment] 2016-09-07 10:54
honestly in my case i think it was as simple as this--the url i copied from my config was https://xxx.herokuapp.com/parse....the one that worked was https://xxx.herokuapp.com/parse/.

Sorry for the bother.

**Comment by taivo** [comment] 2016-09-08 06:23
Ok, no problem. I'll close this issue then.

**Closed by taivo** 2016-09-08 06:23 UTC

**Comment by avril-zilev** [comment] 2017-07-13 20:31
Hi @taivo , I'm using ionic2, but it never creates the installation, is something more what we should change in order to use ionic2 ?,  ParsePushPlugin.getInstallationId is working fine, it gets me an id, but when I check in database the "Installation" class continues empty, do you have any idea what it could be? Thanks in advance

**Comment by cleever** [comment] 2017-07-18 16:58
Strange...

I have ionic1 and ionic2 apps working really well with this plugin, with the pretty same configuration:
```
platform.ready().then(() => {
     if (window['ParsePushPlugin']) {
                ParsePushPlugin.register(function () {

                }, function () {

                });
                ParsePushPlugin.getInstallationId(function (id) {
                    // note that the javascript client has its own installation id,
                    // which is different from the device installation id.
                   alert("device installationId: " + id);
                }, function (e) {
                    alert('error');
                });
```
At config.xml:

```
    <preference name="ParseAppId" value="appid" />
    <preference name="ParseClientKey" value="clientid" />
    <preference name="ParseServerUrl" value="serverurl/" /> <-- Do not forget the backslash at the end
    <preference name="ParseGcmSenderId" value="gcmid" />
    <preference name="ParseAutoRegistration" value="true" />
...
<plugin name="parse-push-plugin" spec="https://github.com/taivo/parse-push-plugin" />
```
That's is all you need to get the plugin working.
All my parse installations require ClientKey.

I think these links may help you:
https://github.com/taivo/parse-push-plugin/issues/52
https://github.com/taivo/parse-push-plugin/pull/57
https://github.com/taivo/parse-push-plugin/issues/79
